# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: QubitPi
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_discussions_categories_limit: 0
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: user
          plugin_gists: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_support: yes
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_trim: no
          plugin_habits_languages_limit: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: TeX
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_aliases: Dockerfile:Docker
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic
          plugin_starlists: yes
          plugin_starlists_limit: 100
          plugin_starlists_limit_repositories: 100
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 100
          plugin_starlists_shuffle_repositories: yes
          plugin_repositories: yes
          plugin_repositories_featured: QubitPi/athena, QubitPi/aristotle
          plugin_calendar: yes
          plugin_calendar_limit: 0
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: starred
          plugin_topics_limit: 20
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.GOOGLE_PAGE_SPEED_TOKEN }}
          plugin_pagespeed_url: https://github.com/QubitPi
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: no
          plugin_pagespeed_pwa: yes
          plugin_stackoverflow: no
          plugin_stackoverflow_user: 14312712
          plugin_stackoverflow_limit: 30
          plugin_stackoverflow_lines: 4
          plugin_stackoverflow_lines_snippet: 999
          plugin_stackoverflow_sections: answers-top, answers-recent, questions-top, questions-recent
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_attachments: yes
          plugin_tweets_limit: 2
          plugin_tweets_user: jack20191124
