# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics (Star Lists - Design & OpenStack)
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: QubitPi
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          filename: github-metrics-starlists-design-openstack.svg
          plugin_starlists: yes
          plugin_starlists_limit: 100
          plugin_starlists_limit_repositories: 100
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 100
          plugin_starlists_shuffle_repositories: yes
          plugin_starlists_only: Design, OpenStack
