name: Restart qubitpi-activity-graph Heroku App
on:
  # Schedule updates (each hour)
  schedule: [{cron: "*/30 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  restart-dyno:
    runs-on: ubuntu-latest
    steps:
     - run: |
        curl -v -n -X DELETE https://api.heroku.com/apps/qubitpi-activity-graph/dynos -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3" -H "Authorization: Bearer ${{ secrets.HEROKU_TOKEN }}"
